Public with sharing Class AppleWatch{
 Public Static void appleWatchmethod(list<Opportunity> lopt ){
    for (Opportunity opp : lopt) {
        Task t        = new Task();
        t.Subject     = 'Apple Watch Promo' ;
        t.Description = 'Send them one ASAP' ;
        t.Priority    = 'High';
        t.WhatId      = opp.Id;
        insert t;
        
        /*line 10 MOD in Dev1*/
        /*line 11*/
        /*line 12*/
        /*line 13*/
        /*line 14*/
        /*line 15*/
        
        /*line 16*/
        /*line 17*/
        /*line 18*/
        /*line 19*/
        /*line 20*/
        
        /*line 21*/
        /*line 22*/
        /*line 23*/
        /*line 24*/
        /*line 25*/
        
        /*line 26*/
        /*line 27*/
        /*line 28*/
        /*line 29*/
        /*line 30*/
        
        /*line 31*/
        /*line 32*/
        /*line 33*/
        /*line 34*/
     
   }
  
  }
 
 }